### ISSUE TITLE
Confusion about unsupervised learning

### ISSUE THREAD

**Issue by chjchjchjchjchj** [ml-jku/DIffUCO#2]
What a nice job! But I have some questions about the concept of "unsupervised". From your codebase, I see that you use GurobiSolver to generate some solutions and energy as the labels, isn't it supervised learning?

**Comment by sanokows** [comment]
Thanks!
The solutions from gurobi are only used to calculate the difference between
the model solutions to the optimal energy value. This difference is then
logged to wandb (e.g. Relative energy).
These solutions are never used for model training. I hope this answer your
question.

Best,

Sebastian Sanokowski

Haojun Chen ***@***.***> schrieb am Mi., 26. Juni 2024, 17:26:
