### ISSUE TITLE
Ask for pretrained weights files

### ISSUE THREAD

**Issue by heatingma** [ml-jku/DIffUCO#4]
Hello, may I ask if you can provide pretrained weights files

**Comment by sanokows** [comment]
Hello, can you give me more information for what kind of problems you want to use the models, i.e. MaxCut or MIS and on wich dataset e.g. RB-small or BA-large?

Also if I have to prove weights it would be useful to know for what purpuse you are planning to use them and until when you need the weights.

Best,

Sebastian

**Comment by heatingma** [comment]
Thank you for your reply. Recently, I have been researching combination optimization problems such as ``MIS``, ``MCut``, and ``MCl``, and I need to cite the paper ``DiffUCO``. However, due to historical issues, it seems that no one has publicly released test datasets. Therefore, I hope you can provide ``.ckpt`` or ``.pt`` files, so that we can test our own generated test datasets within your framework. Below is the list of pre-trained files I need.
* ``MIS``: ``RB-small`` and ``RB-large``
* ``MCut``: ``BA-small`` and ``BA-large``
* ``MaxCl``: ``RB-small``
Thank you very much for your help！

**Comment by sanokows** [comment]
I can provide you weights but these models are better than reported in the original DiffUCO paper. Unfortunately, I do not have the weights as reported in the paper. Does this work for you?
In this case, I would update the code in the repository and add the weights.

**Comment by heatingma** [comment]
I am not very concerned about the specific data in the original paper. If your model can do better, it would also be very helpful to me

**Comment by sanokows** [comment]
I have updated the code and added the weights. 
So first you will have to pull this code from the repo.

A table with the weight ids is given at the end of the README file.

Please let me know if everything works for you.

**Comment by sanokows** [comment]
closed due to inactivity
