### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by luoheyi0514** [ml-jku/DIffUCO#5]
Wow! I got this excellent code from the author. However, I keep getting errors when running it. I really want to know what configuration information needs to be modified! 😃

**Comment by luoheyi0514** [comment]
Wow! I have already revised it extremely carefully according to the author's markdown document! But alas, there are still errors when running it! This is really a bit of a small surprise! However, it doesn't matter. I am sure I can solve the problem and make everything go smoothly!💪

**Comment by luoheyi0514** [comment]
Wow! I have already revised it extremely carefully according to the author's markdown document! But alas, there are still errors when running it! This is really a bit of a small surprise! However, it doesn't matter.

**Comment by luoheyi0514** [comment]
Wow! I have already revised it extremely carefully according to the author's markdown document! But alas, there are still errors when running it! This is really a bit of a small surprise! However, it doesn't matter.

**Comment by sanokows** [comment]
What errors are you getting?

**Comment by luoheyi0514** [comment]
D:\anaconda3\envs\py310\python.exe C:\Users\lhy\Desktop\pre\DIffUCO-main\argparse_ray_main.py 
0
{'mode': 'Diffusion', 'dataset_name': 'RB_iid_100', 'problem_name': 'MIS', 'jit': True, 'wandb': True, 'seed': 123, 'lr': 5e-05, 'batch_size': 30, 'N_basis_states': 10, 'random_node_features': True, 'n_random_node_features': 2, 'relaxed': True, 'T_max': 0.0, 'N_warmup': 0, 'N_anneal': 2000, 'N_equil': 0, 'stop_epochs': 1000, 'n_hidden_neurons': 64, 'n_features_list_prob': [2], 'n_features_list_nodes': [64, 64], 'n_features_list_edges': [64, 64], 'n_features_list_messages': [64, 64], 'n_features_list_encode': [64, 64], 'n_features_list_decode': [64, 64], 'n_message_passes': 8, 'message_passing_weight_tied': False, 'linear_message_passing': True, 'edge_updates': False, 'n_diffusion_steps': 10, 'beta_factor': 1.0, 'noise_potential': 'annealed_obj', 'time_conditioning': True, 'project_name': '', 'mean_aggr': True, 'grad_clip': True, 'messeage_concat': False, 'graph_mode': 'normal', 'loss_alpha': 0.0, 'MCMC_steps': 0, 'train_mode': 'REINFORCE', 'inner_loop_steps': 1, 'minib_diff_steps': 3, 'minib_basis_states': 10, 'graph_norm': True, 'proj_method': 'None', 'diff_schedule': 'DiffUCO', 'mov_average': 0.0009, 'lr_schedule': False, 'eval_step_factor': 1}
pad_k is 1.3
noise potential annealed_obj
beta is
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
______________
EVAL STEP FACTOR is 1
D:\anaconda3\envs\py310\lib\site-packages\torch\utils\data\dataloader.py:617: UserWarning: This DataLoader will create 40 worker processes in total. Our suggested max number of worker in current system is 32 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
Training is distributed across  1 devices!
pmapped params
{'params': {'HeadModel': {'probMLP': {'mlp': {'layers_0': {'bias': (1, 120), 'kernel': (1, 64, 120)}, 'layers_2': {'bias': (1, 120), 'scale': (1, 120)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 120, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_6': {'bias': (1, 2), 'kernel': (1, 64, 2)}}}}, 'encode_process_decode': {'node_decoder': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'node_encoder': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 14, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'process_block_0': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_1': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_2': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_3': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_4': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_5': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_6': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}, 'process_block_7': {'GraphNorm': {'bias': (1, 64), 'mean_scale': (1, 64), 'scale': (1, 64)}, 'LayerNorm': {'bias': (1, 64), 'scale': (1, 64)}, 'NodeMLP': {'mlp': {'layers_0': {'bias': (1, 64), 'kernel': (1, 128, 64)}, 'layers_2': {'bias': (1, 64), 'scale': (1, 64)}, 'layers_3': {'bias': (1, 64), 'kernel': (1, 64, 64)}, 'layers_5': {'bias': (1, 64), 'scale': (1, 64)}}}, 'W_message': {'kernel': (1, 65, 64)}, 'W_node': {'kernel': (1, 64, 64)}}}}}
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: luoheyi0514 (luoheyi0514-institution). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.5
wandb: Run data is saved locally in C:\Users\lhy\Desktop\pre\DIffUCO-main\wandb\run-20241106_135437-hmt0bu42
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run None_hmt0bu42_lr_5e-05_nh_64_time_cond_True_n_diff_10_deeper
wandb:  View project at https://wandb.ai/luoheyi0514-institution/Diffusion_RB_iid_100_MIS_relaxed_True_deeper
wandb:  View run at https://wandb.ai/luoheyi0514-institution/Diffusion_RB_iid_100_MIS_relaxed_True_deeper/runs/hmt0bu42
first evaluation...
D:\anaconda3\envs\py310\lib\site-packages\torch\utils\data\dataloader.py:617: UserWarning: This DataLoader will create 40 worker processes in total. Our suggested max number of worker in current system is 32 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(
batchsize is 30
function is being jitted
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\argparse_ray_main.py", line 305, in <module>
    meanfield_run()
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\argparse_ray_main.py", line 119, in meanfield_run
    detect_and_run_for_loops()
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\argparse_ray_main.py", line 212, in detect_and_run_for_loops
    run(flexible_config=flexible_config, overwrite=True)
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\argparse_ray_main.py", line 292, in run
    train.train()
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\train.py", line 537, in train
    self.eval(epoch=0)
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\train.py", line 670, in eval
    loss, (log_dict, _) = self.TrainerClass.evaluation_step(self.params, graph_batch, energy_graph_batch, self.T, batched_key, mode = mode)
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\Trainers\BaseTrainer.py", line 70, in evaluation_step
    loss, (log_dict, _) = self.pmap_sample(params, graph_batch, energy_graph_batch, T, batched_key)
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\Trainers\REINFORCE_Trainer.py", line 21, in sample
    return self.diffusion_loss(params, graphs, energy_graph_batch, T, key)
  File "C:\Users\lhy\Desktop\pre\DIffUCO-main\Trainers\REINFORCE_Trainer.py", line 110, in diffusion_loss
    X_prev, one_hot_state, log_p_uniform, key = self.model.sample_prior(energy_graph_batch, self.N_basis_states, key)
ValueError: Jitted function has static_argnums=(0, 4), but only accepts 4 positional arguments.
wandb: 🚀 View run None_hmt0bu42_lr_5e-05_nh_64_time_cond_True_n_diff_10_deeper at: https://wandb.ai/luoheyi0514-institution/Diffusion_RB_iid_100_MIS_relaxed_True_deeper/runs/hmt0bu42
wandb: Find logs at: wandb\run-20241106_135437-hmt0bu42\logs

进程已结束，退出代码为 1

**Comment by luoheyi0514** [comment]
[报错代码.txt](https://github.com/user-attachments/files/17642377/default.txt)

**Comment by sanokows** [comment]
Thank you for bringing this into my attention. 
Can you also send me the command with which you ran the code?

I will look into this within the next few days.

**Comment by luoheyi0514** [comment]
python argparse_ray_main.py --lrs 0.002 --GPUs 0 --n_GNN_layers 8 --temps 0.6 --IsingMode RB_iid_100 --EnergyFunction MIS --N_anneal 2000 
--n_diffusion_steps 3 --batch_size 20 --n_basis_states 10 --noise_potential bernoulli --project_name FirstRuns --seed 123

**Comment by sanokows** [comment]
I have updated the code and it works for me.
Can you pull the latest code from the main branch and try it again?
Please let me know if it works.

**Comment by luoheyi0514** [comment]
The current code can run, but my graphics card is not very good. Thank you for your reply.

**Comment by luoheyi0514** [comment]
The current code can run, but my graphics card is not very good. Thank you for your reply.

**Comment by sanokows** [comment]
Thanks for the feedback.
I will close this issue. If you have further questions feel free to open up a new issue.
