### ISSUE TITLE
关于论文16页 Joint Variational Diffusion Model Objective 的推导

### ISSUE THREAD

**Issue by luoheyi0514** [ml-jku/DIffUCO#6]
![微信图片编辑_20241116220601](https://github.com/user-attachments/assets/816ecbe9-6e1c-40f9-90c1-5d64b2995ecd)

这个地方是不是要修改为我图片标记的 因为记录的是反向扩散的过程？ 希望师兄解答一下 谢谢

**Comment by sanokows** [comment]
I think it is fine to write it down in both ways.
I agree that changing the notation in the way as you proposed it would make it clearer that generation starts at T and ends at 0.
